const englishWords = [
  "act", "add", "alert", "alpha", "apple", "apply", "arena", "argue", "arrow", "ask", "asset", "attach",
  "back", "bag", "ball", "band", "bank", "base", "bat", "bear", "beat", "bed", "bee", "bell", "best", "beta", "bike", "bill",
  "bird", "blade", "blank", "blast", "block", "blog", "blue", "board", "boat", "body", "bold", "bomb", "book", "boom", "boot",
  "boss", "bottom", "box", "boy", "brain", "brave", "bread", "break", "brick", "bridge", "brief", "bring", "brush", "bubble",
  "build", "bulk", "bus", "buy", "buzz", "cake", "call", "calm", "camp", "can", "candy", "cap", "card", "care", "carry",
  "case", "cash", "cast", "catch", "cause", "chain", "chair", "chalk", "change", "chart", "chat", "check", "cheer", "chess",
  "chief", "choose", "chop", "clean", "clear", "click", "clock", "close", "cloth", "cloud", "club", "code", "coffee",
  "cold", "color", "come", "comment", "common", "cool", "copy", "cost", "count", "cover", "crash", "crazy", "create",
  "credit", "crew", "crop", "cross", "cry", "cube", "cut", "cycle", "daily", "dance", "dark", "dash", "data", "date",
  "day", "dead", "deal", "debug", "deck", "deep", "delete", "delta", "deny", "desk", "design", "develop", "dice",
  "die", "dig", "dine", "dive", "door", "dot", "down", "download", "drag", "draw", "dream", "dress", "drill", "drink",
  "drive", "drop", "drum", "dry", "duck", "dust", "duty", "each", "earn", "earth", "edge", "edit", "egg", "eight", "end",
  "enter", "epic", "equal", "error", "event", "every", "exact", "exit", "expand", "extra", "eye", "face", "fact", "fail",
  "fall", "fast", "fasten", "fault", "fear", "feed", "feel", "fetch", "fight", "file", "fill", "filter", "final", "find",
  "fine", "fire", "firm", "first", "fish", "fix", "flag", "flat", "flip", "flow", "fly", "focus", "fog", "foggy", "fold",
  "follow", "food", "foot", "force", "form", "forward", "fox", "frame", "free", "fresh", "front", "fun", "funny",
  "game", "gap", "gas", "gate", "gather", "gift", "girl", "give", "glass", "globe", "go", "goal", "gold", "golf", "good",
  "grab", "grade", "grain", "graph", "great", "green", "group", "grow", "guess", "guide", "gun", "habit", "half", "hall",
  "hand", "happy", "hard", "harm", "hat", "hate", "have", "head", "health", "hear", "heat", "heavy", "hello", "help",
  "hide", "high", "hill", "hint", "hit", "hold", "hole", "home", "hope", "horse", "hot", "hotel", "hour", "house", "how",
  "ice", "idea", "image", "impact", "index", "info", "input", "issue", "item", "join", "joke", "jump", "key", "kick",
  "kid", "kill", "kind", "king", "kiss", "kite", "knee", "knock", "lamp", "land", "last", "late", "laugh", "lava",
  "law", "lay", "lead", "leaf", "learn", "leave", "left", "leg", "lend", "less", "let", "level", "life", "lift", "light",
  "like", "limit", "line", "link", "lion", "list", "listen", "live", "load", "lock", "log", "logic", "long", "look",
  "loop", "lose", "loud", "love", "lucky", "magic", "map", "mark", "match", "maximize", "mention",
  "mind", "minimize", "move", "mud", "mute", "nail", "navigate", "need", "new", "nice", "night",
  "no", "note", "now", "off", "old", "on", "open", "output", "page", "paint", "pair", "part", "paste",
  "path", "pause", "peace", "pen", "phone", "pin", "plan", "plane", "play", "plug", "post", "power",
  "print", "pull", "push", "quick", "rain", "rate", "read", "receive", "record", "refresh", "remove",
  "repeat", "reply", "report", "reset", "restart", "resume", "rewind", "right", "ring", "rise",
  "risk", "road", "rock", "roll", "room", "rope", "run", "same", "save", "scan", "screw", "scroll",
  "search", "select", "send", "share", "shark", "sharp", "shift", "ship", "show", "shuffle", "sign",
  "silver", "sit", "sketch", "skill", "slow", "smart", "smile", "snap", "snow", "soon", "sort",
  "sound", "speed", "spin", "stand", "start", "stay", "steel", "stop", "storm", "stream", "strong",
  "subscribe", "sunny", "super", "switch", "sword", "tag", "take", "teach", "tent", "test", "then",
  "think", "tiger", "top", "track", "train", "tree", "trust", "truth", "try", "turn", "tweet", "type",
  "unblock", "uncheck", "unfollow", "unity", "unlike", "unlock", "unmute", "unpin", "unsubscribe",
  "up", "update", "upload", "value", "view", "vote", "wait", "walk", "watch", "wave", "whale", "win",
  "windy", "wire", "wise", "wish", "world", "write", "yes", "zebra", "zoom"
];

  export default englishWords;